### ISSUE TITLE
Problem importing Scanorama: dependency sklearn.externals.six

### ISSUE THREAD

**Issue by auesro** [brianhie/scanorama#100]
I have used Scanorama previously (more than 1 year ago) but today I am getting an error on import:
```
import scanorama
Traceback (most recent call last):

  File "/tmp/ipykernel_22000/104445913.py", line 1, in <module>
    import scanorama

  File "/home/auesro/anaconda3/envs/Scanpy/lib/python3.7/site-packages/scanorama/__init__.py", line 1, in <module>
    from .scanorama import *

  File "/home/auesro/anaconda3/envs/Scanpy/lib/python3.7/site-packages/scanorama/scanorama.py", line 16, in <module>
    from .t_sne_approx import TSNEApprox

  File "/home/auesro/anaconda3/envs/Scanpy/lib/python3.7/site-packages/scanorama/t_sne_approx.py", line 31, in <module>
    from sklearn.externals.six import string_types

ModuleNotFoundError: No module named 'sklearn.externals.six'
```
From what I can see, `sklearn.externals.six` was dropped on scikit-learn version 0.21 as shown [here](https://scikit-learn.org/stable/whats_new/v0.21.html?highlight=externals%20six#sklearn-externals).
I could downgrade `scikit-learn` to 0.21 I guess but thats borderline with Python 3.7 support...any other solutions?

**Comment by auesro** [comment]
Hi @brianhie,
Problem solved. Indeed updating scanorama takes care of the issue.
Only to notice, I got a warning from pip:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
spyder 5.1.5 requires intervaltree>=3.0.2, but you have intervaltree 2.1.0 which is incompatible.
```
This obviously only affects Spyder users, so I just updated intervaltree to 3.0.2 and will check if Scanorama can run. If possible, check this out.

A
