### ISSUE TITLE
IndexError('index (%d) out of range' % max_indx)

### ISSUE THREAD

**Issue by yafeng** [brianhie/scanorama#106]
Hi,
i got the following indexError whiling runing `scanorama$correct`

`
# List of datasets (matrices of cells-by-genes):
datasets <- list( matrix1, matrix2 )
# List of gene lists:
genes_list <- list(rownames(matrix1), rownames(matrix2))

# Batch correction.
corrected.data <- scanorama$correct(datasets, genes_list, return_dense=TRUE)
`

the dimension of matrix1, matrix 2 is (1454,108), (1228,72)
The error message is :
`
Found 987 genes among all datasets
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/Documents/github/scanorama/scanorama/scanorama.py", line 171, in integrate
    ds_names=ds_names, union=union)
  File "~/Documents/github/scanorama/scanorama/scanorama.py", line 362, in merge_datasets
    datasets[i] = datasets[i][:, uniq_idx]
  File "~/miniconda3/envs/sceptre/lib/python3.7/site-packages/scipy/sparse/_index.py", line 33, in __getitem__
    row, col = self._validate_indices(key)
  File "~/miniconda3/envs/sceptre/lib/python3.7/site-packages/scipy/sparse/_index.py", line 147, in _validate_indices
    col = self._asindices(col, N)
  File "~/miniconda3/envs/sceptre/lib/python3.7/site-packages/scipy/sparse/_index.py", line 170, in _asindices
    raise IndexError('index (%d) out of range' % max_indx)
IndexError: index (1453) out of range
`
Do you know what caused the error ?

**Comment by brianhie** [comment]
Could you make sure that when using Scanorama, the input matrices are cell-by-gene and not gene-by-cell? In R the convention often uses the matrix transpose
