### ISSUE TITLE
Interval tree version bump?

### ISSUE THREAD

**Issue by ivirshup** [brianhie/scanorama#115]
The pinned version of `intervaltree` can't be imported with python 3.10.

```sh
$ mamba create -yn intervaltree python=3.10
# ...
$ conda activate intervaltree
# ...
$ pip install "intervaltree==2.1.0"
# ...
$ python -c "import intervaltree"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/isaac/miniconda3/envs/intervaltree/lib/python3.10/site-packages/intervaltree/__init__.py", line 22, in <module>
    from .intervaltree import IntervalTree
  File "/Users/isaac/miniconda3/envs/intervaltree/lib/python3.10/site-packages/intervaltree/intervaltree.py", line 37, in <module>
    class IntervalTree(collections.MutableSet):
AttributeError: module 'collections' has no attribute 'MutableSet'
```

Could the pinned version get a bump?

**Comment by ivirshup** [comment]
Great, thanks!
