### ISSUE TITLE
ValueError: blocks must be 2-D

### ISSUE THREAD

**Issue by grst** [brianhie/scanorama#17]
Hi, 

I encounter the following error when running scanorama:
```
Found 105476 cells among all datasets
After data/293t_jurkat/293t: 32639 genes
After data/293t_jurkat/jurkat: 32639 genes
After data/293t_jurkat/jurkat_293t_50_50: 32639 genes
After data/293t_jurkat/jurkat_293t_99_1: 32639 genes
After data/brain/neuron_9k: 15642 genes
After data/macrophage/infected: 12731 genes
After data/macrophage/mixed_infected: 11622 genes
After data/macrophage/uninfected: 10510 genes
After data/macrophage/uninfected_donor2: 9414 genes
After data/hsc/hsc_mars: 5386 genes
After data/hsc/hsc_ss2: 5328 genes
After data/pancreas/pancreas_inDrop: 5311 genes
After data/pancreas/pancreas_multi_celseq2_expression_matrix: 5298 genes
After data/pancreas/pancreas_multi_celseq_expression_matrix: 5286 genes
After data/pancreas/pancreas_multi_fluidigmc1_expression_matrix: 5216 genes
After data/pancreas/pancreas_multi_smartseq2_expression_matrix: 5216 genes
After data/pbmc/10x/68k_pbmc: 5216 genes
After data/pbmc/10x/b_cells: 5216 genes
After data/pbmc/10x/cd14_monocytes: 5216 genes
After data/pbmc/10x/cd4_t_helper: 5216 genes
After data/pbmc/10x/cd56_nk: 5216 genes
After data/pbmc/10x/cytotoxic_t: 5216 genes
After data/pbmc/10x/memory_t: 5216 genes
After data/pbmc/10x/regulatory_t: 5216 genes
After data/pbmc/pbmc_kang: 5216 genes
After data/pbmc/pbmc_10X: 5216 genes
Found 5216 genes among all datasets
Traceback (most recent call last):
  File "bin/panorama.py", line 17, in <module>
    return_dimred=True
  File "/storage/home/sturm/projects/single_cell_data_integration/scanorama/scanorama/scanorama.py", line 89, in correct
    datasets_dimred, genes = process_data(datasets, genes, hvg=hvg)
  File "/storage/home/sturm/projects/single_cell_data_integration/scanorama/scanorama/scanorama.py", line 343, in process_data
    datasets_dimred = dimensionality_reduce(datasets, dimred=dimred)
  File "/storage/home/sturm/projects/single_cell_data_integration/scanorama/scanorama/scanorama.py", line 308, in dimensionality_reduce
    X = vstack(datasets)
  File "/storage/home/sturm/.conda/envs/scanorama2/lib/python2.7/site-packages/scipy/sparse/construct.py", line 498, in vstack
    return bmat([[b] for b in blocks], format=format, dtype=dtype)
  File "/storage/home/sturm/.conda/envs/scanorama2/lib/python2.7/site-packages/scipy/sparse/construct.py", line 547, in bmat
    raise ValueError('blocks must be 2-D')
ValueError: blocks must be 2-D
```

## Steps to reproduce:
```
git clone git@github.com:brianhie/scanorama.git
cd scanorama
pip install -e . 
wget http://scanorama.csail.mit.edu/data_light.tar.gz
tar xvzf data_light.tar.gz
python bin/preprocess.py conf/panorama.txt
python bin/panorama.py conf/panorama.txt
```

## Environment
Here's a conda enviroment in that the problem occurs. 

**scanorama.yml**
```
name: scanorama
channels:
  - conda-forge
  - bioconda
  - defaults
  - grst
dependencies:
  - python=2.7
  - docopt=0.6.2
  - python-annoy=1.11.5
  - intervaltree=2.1.0
  - matplotlib=2.0.2
  - networkx=2.1
  - numpy=1.12.0
  - scipy=1.0.0
  - scikit-learn=0.19.1
  - statsmodels=0.8.0
  - pip:
    - fbpca==1.0
```

Actually, I also tried with python 3.6 and more recent versions of the packages - with the same result.

**Comment by brianhie** [comment]
Hi @grst, that error message probably indicates that the data sets being passed to Scanorama are dense matrices (i.e, `np.ndarray`) and not sparse matrices (i.e., `scipy.sparse.csr_matrix`). There was a recent change in Scanorama where the `bin/process.py` stores the processed matrices as sparse and not dense.

Could you try rerunning and reprocessing with the latest version? I.e.
```
git clone git@github.com:brianhie/scanorama.git
cd scanorama
wget http://scanorama.csail.mit.edu/data_light.tar.gz
tar xvzf data_light.tar.gz
python setup.py install --user
python bin/process.py conf/panorama.txt
python bin/panorama.py conf/panorama.txt
```

**Comment by grst** [comment]
I performed all steps today in a clean conda environment.

**Comment by brianhie** [comment]
Oops really sorry about that, fixed in https://github.com/brianhie/scanorama/pull/18

Please rebase and try again

**Comment by grst** [comment]
Seems to work now 🎉 
thanks, @brianhie!

**Comment by brianhie** [comment]
@grst Awesome, apologies for the hiccup and let me know if you have any more questions!
