### ISSUE TITLE
pip release 0.6.2 ModuleNotFoundError

### ISSUE THREAD

**Issue by alex-wenzel** [brianhie/scanorama#28]
I used pip to install scanorama version 0.6.2 and ran

```python 
import scanorama
```

with Python 3.6, which resulted in 

```python
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-4ea9f8d58e85> in <module>()
----> 1 import scanorama

/opt/conda/lib/python3.6/site-packages/scanorama/__init__.py in <module>()
----> 1 from .scanorama import *

/opt/conda/lib/python3.6/site-packages/scanorama/scanorama.py in <module>()
     15 
     16 from .t_sne_approx import TSNEApprox
---> 17 from .integration import harmony_integrate
     18 from .utils import plt, dispersion, reduce_dimensionality
     19 from .utils import visualize_cluster, visualize_expr, visualize_dropout

/opt/conda/lib/python3.6/site-packages/scanorama/integration.py in <module>()
----> 1 from ample import gs, uniform, srs, kmeanspp
      2 import numpy as np
      3 from subprocess import Popen
      4 from time import time
      5 

ModuleNotFoundError: No module named 'ample'
```

Google searches aren't immediately showing what the "ample" module might be - is it misspelled? Uninstalling and reverting to version 0.6 fixes this issue. Let me know if I can provide any more information.

**Comment by brianhie** [comment]
@alex-wenzel Oops sorry! Fixed in 0.7

Ample is an experimental package that we hope to unveil soon :)

**Comment by alex-wenzel** [comment]
Thanks for the quick response. I encountered this error when trying to install version 0.7. It appears to be an issue with one of the dependencies.

```
Collecting scanorama==0.7.0
  Downloading https://files.pythonhosted.org/packages/71/7c/9ee31fb69e96a25fe7555d575595225d6ea713616a7077d71a5b863eca84/scanorama-0.7.tar.gz
Collecting annoy>=1.11.5 (from scanorama==0.7.0)
  Downloading https://files.pythonhosted.org/packages/b5/28/f8ce7400344090bb5cfa1c9fae3fdb03b9438db082d458686442633d82a3/annoy-1.15.0.tar.gz (635kB)
Collecting fbpca>=1.0 (from scanorama==0.7.0)
  Downloading https://files.pythonhosted.org/packages/a7/a5/2085d0645a4bb4f0b606251b0b7466c61326e4a471d445c1c3761a2d07bc/fbpca-1.0.tar.gz
Collecting intervaltree>=2.1.0 (from scanorama==0.7.0)
  Downloading https://files.pythonhosted.org/packages/6b/63/42329a3e503366be2be68384336db308a795516b362437368ddd82d3368f/intervaltree-3.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-huon1yux/intervaltree/setup.py", line 60, in <module>
        long_description = fh.read()
      File "/opt/conda/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 5223: ordinal not in range(128)
    !!!>>> This is a RELEASE version <<<!!!
    
    Version: 3.0.1
    
    ----------------------------------------

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-huon1yux/intervaltree/
```

**Comment by brianhie** [comment]
Yikes, looks like a problem with intervaltree v3, try installing intervaltree==2.1.0 and then installing scanorama? I’ll look into modifying the dependencies in setup.py as well

**Comment by alex-wenzel** [comment]
That fixed it, thanks!

**Comment by brianhie** [comment]
Awesome! I’ll change to intervaltree==2.1.0 for now

**Comment by brianhie** [comment]
@alex-wenzel Ok, dependency enforced: https://github.com/brianhie/scanorama/commit/422fd75751b886ab02291f91076bf7ea7fa80b7e#diff-2eeaed663bd0d25b7e608891384b7298
