### ISSUE TITLE
Maybe fix __version__?

### ISSUE THREAD

**Issue by Puriney** [brianhie/scanorama#60]
https://github.com/brianhie/scanorama/blob/f2435c418e56babc205165b0383e7407dd96c737/scanorama/__init__.py#L3

```
>>> import scanorama
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "anaconda3/lib/python3.6/site-packages/scanorama/__init__.py", line 3
    __version__ = 1.5.1
                      ^
SyntaxError: invalid syntax
```

If I change to `__version__ = "1.5.1"`, it will work.

**Comment by brianhie** [comment]
that's embarrassing! should be fixed now
